// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoeykrqwyvofehpcyyhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZXlrcnF3eXZvZmVocGN5eWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTk4MTgsImV4cCI6MjA2NTI3NTgxOH0.8Dw4MDzwVHfg1IGthIHCNuuiRRaEawDdDURnjvwsP_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);