// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hchqflytwlealoavgbih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaHFmbHl0d2xlYWxvYXZnYmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDg0NTgsImV4cCI6MjA2NDg4NDQ1OH0.VkuU7jFaz2N65q2XBm6nLelpBM8i9dl-39VOexv4VeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);